# Generated by Django 3.1.3 on 2020-11-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=64)),
                ('project_type', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('page_url', models.URLField()),
                ('github_url', models.URLField()),
            ],
        ),
    ]
