# Generated by Django 3.1.3 on 2020-12-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_auto_20201129_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWebpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='intro/images/')),
                ('title', models.CharField(max_length=64)),
                ('project_type', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('page_url', models.URLField()),
                ('github_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='intro/images/')),
                ('title', models.CharField(max_length=64)),
                ('project_type', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('page_url', models.URLField()),
                ('github_url', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectFunWebpage',
        ),
    ]
